kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: obc-sa-admin
subjects:
  - kind: ServiceAccount
    name: flask-obc-sa
    namespace: flask-obc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmap-secret-obc-manager

